### ISSUE TITLE
"Module build failed" error

### ISSUE THREAD

**Issue by dmarti** [filterbubbler/filterbubbler-web-ext#19]
ERROR in ./src/content.js
Module build failed: ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in "/home/dmarti/Projects/filterbubbler-web-ext/.babelrc" at 2, attempted to resolve relative to "/home/dmarti/Projects/filterbubbler-web-ext"
    at /home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-loader/lib/index.js:41:20)
    at Object.module.exports (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-loader/lib/index.js:138:12)

ERROR in ./src/popup.js
Module build failed: ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in "/home/dmarti/Projects/filterbubbler-web-ext/.babelrc" at 2, attempted to resolve relative to "/home/dmarti/Projects/filterbubbler-web-ext"
    at /home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-loader/lib/index.js:41:20)
    at Object.module.exports (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-loader/lib/index.js:138:12)
 @ multi popup

ERROR in ./src/background.js
Module build failed: ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in "/home/dmarti/Projects/filterbubbler-web-ext/.babelrc" at 2, attempted to resolve relative to "/home/dmarti/Projects/filterbubbler-web-ext"
    at /home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-loader/lib/index.js:41:20)
    at Object.module.exports (/home/dmarti/Projects/filterbubbler-web-ext/node_modules/babel-loader/lib/index.js:138:12)

**Comment by schue** [comment]
I'm surprised that babel-preset-es2015 doesn't pull this in. I need to replicate it locally. What versions of Node and NPM are you running?

**Comment by schue** [comment]
Is this resolved? Can we close?

**Comment by dmarti** [comment]
yes, it's working for me now.
